#+title: AWS Academy Notes
#+author: Bard-Gaming
#+date: Mon Jun  2 11:41:02 2025


*** Structure
This repository is organised into the 10 different modules
that are required to obtain the Cloud Practitioner certificate.

These are:
# Note: using "file:" syntax breaks GitHub apparently.
- [[./Module 1][Module 1: Cloud Concepts]]
- [[./Module 2][Module 2: Cloud Economics and Billing]]
- [[./Module 3][Module 3: AWS Global Infrastructure]]
- [[./Module 4][Module 4: AWS Cloud Security]]
- [[./Module 5][Module 5: Network and Content Delivery]]
- others yet to come.

All modules have a general overview in their README.
You are free to browse this repository as you please.


*** Feedback
For feedback, please [[https://github.com/Bard-Gaming/AWS-Academy/issues/new][create an issue]]!

Feedback is highly appreciated! Thank you \(°v°)/


*** Credits
Everything here is owned by AWS Academy.
I am merely creating a text support to allow future
cloud practitioners to have an easier time learning.
Enjoy !
